### ISSUE TITLE
RDPWrapper-Portable@1.6.2: hash check failed

### ISSUE THREAD

**Issue by cheneric0929** [ACooper81/scoop-apps#14]
Checking hash of autoupdate.zip ... ERROR Hash check failed!
App:         Scoop-Apps/RDPWrapper-Portable
URL:         https://raw.githubusercontent.com/asmtron/rdpwrap/master/autoupdate.zip#/auto.alfa
First bytes: 50 4B 03 04 14 00 00 00
Expected:    2e16b3f6cb22ce6643a5cedcf0babec1588c11954c27e669a420346ca3ce9583
Actual:      2a12fc292430f9d6978335113f616dd58a70d1b021b175870b56ae7cfe41634f

**Comment by ACooper81** [comment]
Sorry for the delay. I have updated the hash for the file now.
