### ISSUE TITLE
AdobeAcrobatReader-Install: ERROR Exit code was 1639!

### ISSUE THREAD

**Issue by sonofjon** [ACooper81/scoop-apps#16]
scoop install AdobeAcrobatReader-Install
Installing 'AdobeAcrobatReader-Install' (22.001.20117) [64bit]
Loading AcroRdrDCUpd2200120117.msp from cache.
Checking hash of AcroRdrDCUpd2200120117.msp ... ok.
Running pre-install script...
Running installer script...
ERROR Exit code was 1639!

**Comment by ACooper81** [comment]
I have updated the AdobeAcrobatReader-Install manifest to install the MUI version of the install files. You might have to uninstall Acrobat Reader and let scoop install the MUI version. Hope this helps.

**Comment by sonofjon** [comment]
Hi, now the installation gets a bit further. I get a window where I can click OK. But then there is an error again:

> scoop install AdobeAcrobatReader-Install
Installing 'AdobeAcrobatReader-Install' (22.001.20117) [64bit]
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 1d7e80|OK  |    16MiB/s|C:/Users/Andreas Jonsson/scoop/cache/AdobeAcrobatReader-Install#22.001.20117#https_ardownload2.adobe.com_pub_adobe_reader_win_AcrobatDC_2200120117_AcroRdrDCUpd2200120117_MUI.msp_setup.msp_
Download: Status Legend:
Download: (OK):download completed.
Checking hash of AcroRdrDCUpd2200120117_MUI.msp ... ok.
Running pre-install script...
Running installer script...
ERROR Exit code was 1639!

**Comment by ACooper81** [comment]
Can you give it another try now? I think I have fixed the 1639 error now.

**Comment by sonofjon** [comment]
It works now, installs without error, and the application runs fine. However, during installation I get the following notification

![image](https://user-images.githubusercontent.com/7573435/172124932-392bfd4b-20fe-47ff-918b-d829b183786f.png)

**Comment by ACooper81** [comment]
I think this is Microsoft not wanting software to change file type associations. If you set the default manually you should be fine.
