### ISSUE TITLE
Error on NoMachine-Install install

### ISSUE THREAD

**Issue by sonofjon** [ACooper81/scoop-apps#17]
Installing 'NoMachine-Install' (7.9.2) [64bit]
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 7f81f0|OK  |   7.3MiB/s|C:/Users/sonof/scoop/cache/NoMachine-Install#7.9.2#https_download.nomachine.com_download_7.9_Windows_nomachine_7.9.2_1.exe_setup.exe
Download: Status Legend:
Download: (OK):download completed.
Checking hash of nomachine_7.9.2_1.exe ... ok.
Running pre-install script...
Running installer script...
Linking ~\scoop\apps\NoMachine-Install\current => ~\scoop\apps\NoMachine-Install\7.9.2
Running post-install script...
Remove-Item : Cannot remove item C:\Users\Public\Desktop\NoMachine.lnk: Access to the path is denied.
At line:3 char:55
+ ... name.lnk") {Remove-Item "$CommonDesktopPath\$programname.lnk" -Force} ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (C:\Users\Public\Desktop\NoMachine.lnk:FileInfo) [Remove-Item], Argumen
   tException
    + FullyQualifiedErrorId : RemoveFileSystemItemArgumentError,Microsoft.PowerShell.Commands.RemoveItemCommand
'NoMachine-Install' (7.9.2) was installed successfully!

**Comment by ACooper81** [comment]
It looks like you don't have rights to delete the file from the Public Desktop folder. Can you delete the shortcut manually?

**Comment by sonofjon** [comment]
Yes, I then uninstalled and installed again, and it worked prefectly. Thanks!
