### ISSUE TITLE
Streamlink Twitch GUI has the wrong package name

### ISSUE THREAD

**Issue by bastimeyer** [ACooper81/scoop-apps#26]
Hi, I'm the author of [Streamlink Twitch GUI](https://github.com/streamlink/streamlink-twitch-gui) and just found this via a Google search result on https://rasa.github.io/scoop-directory/search.

My application is packaged in your scoop bucket as `StreamlabsTwitchGUI-Portable`, which is wrong:
https://github.com/ACooper81/scoop-apps/blob/b52fbbaf7c9d56bdd4c74807b47020fb5911e1cd/bucket/StreamlabsTwitchGUI-Portable.json

Since I am not a user of scoop or even Windows, I don't want to submit a PR with a rename of the file, so I'm opening this issue instead and would like to kindly ask you to rename it yourself.

Thanks.

**Comment by ACooper81** [comment]
I have changed the name of the package now. Sorry for the mixup.
