### ISSUE TITLE
dismplusplus-portable@10.1.1002.2: download via aria2 failed

### ISSUE THREAD

**Issue by jjaymcdaniel** [ACooper81/scoop-apps#353]
Updating 'dismplusplus-portable' (10.1.1002.1 -> 10.1.1002.2)
Downloading new version
Starting download with aria2 ...
Download: 08/09 21:38:32 [ERROR] CUID#8 - Download aborted. URI=https://github.com/Chuyu-Team/Dism-Multi-language/releasDownload: Exception: [AbstractCommand.cc:351] errorCode=3 URI=https://github.com/Chuyu-Team/Dism-Multi-language/releasesDownload: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: e65be0|ERR |       0B/s|C:/ProgramFiles/Scoop/cache/dismplusplus-portable#10.1.1002.2#https_github.com_Chuyu-Team_Dism-Multi-language_releases_download_v10.1.1002.2_Dism_10.1.1002.18.zip
Download: Status Legend:
Download: (ERR):error occurred.
Download: aria2 will resume download if the transfer is restarted.
Download: If there are any errors, then see the log file. See '-l' option in help/man page for details.

ERROR Download failed! (Error 3) Resource was not found
ERROR https://github.com/Chuyu-Team/Dism-Multi-language/releases/download/v10.1.1002.2/Dism++10.1.1002.18.zip
    referer=https://github.com/Chuyu-Team/Dism-Multi-language/releases/download/v10.1.1002.2/
    dir=C:\ProgramFiles\Scoop\cache
    out=dismplusplus-portable#10.1.1002.2#https_github.com_Chuyu-Team_Dism-Multi-language_releases_download_v10.1.1002.2_Dism_10.1.1002.18.zip

ERROR & 'c:\ProgramFiles\ScoopGlobal\apps\aria2\current\aria2c.exe' --input-file='C:\ProgramFiles\Scoop\cache\dismplusplus-portable.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/7.3 (Windows NT 10.0; Win64; x64; Core)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=19216 --continue --summary-interval=0 --auto-save-interval=1

**Comment by ACooper81** [comment]
I have updaed the URL so it should work now.
