### ISSUE TITLE
WindowsTerminal-Portable@1.15.2524.0: decompress error

### ISSUE THREAD

**Issue by areen-c** [ACooper81/scoop-apps#44]
Package: WindowsTerminal-Portable
Version: [v1.15.2524.0](https://github.com/ACooper81/scoop-apps/blob/master/bucket/WindowsTerminal-Portable.json)
App: Scoop-Apps/WindowsTerminal-Portable

`Installing 'WindowsTerminal-Portable' (1.15.2524.0) [64bit] from ACooper81_scoop-apps bucket
Loading Microsoft.WindowsTerminal_Win10_1.15.2524.0_8wekyb3d8bbwe.msixbundle from cache.
Checking hash of Microsoft.WindowsTerminal_Win10_1.15.2524.0_8wekyb3d8bbwe.msixbundle ... ok.
Running pre_install script...
Running installer script...
Split-Path: C:\Users\ariku\scoop\apps\scoop\current\lib\decompress.ps1:30
Line |
  30 |      $LogPath = "$(Split-Path $Path)\7zip.log"
     |                               ~~~~~
     | Cannot bind argument to parameter 'Path' because it is an empty string.

ERROR Exit code was 7!
Failed to extract files from .
Log file:
  \7zip.log`

**Comment by ACooper81** [comment]
I think the problem has been fixed now. Let me know how you go.

**Comment by areen-c** [comment]
> I think the problem has been fixed now. Let me know how you go.

`Installing 'WindowsTerminal-Portable' (1.15.2524.0) [64bit] from ACooper81_scoop-apps bucket
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 8bd46e|OK  |   859KiB/s|C:/Users/ariku/scoop/cache/WindowsTerminal-Portable#1.15.2524.0#https_github.com_microsoft_terminal_releases_download_v1.15.2524.0_Microsoft.WindowsTerminal_Win10_1.15.2524.0_8wekyb3d8bbwe.msixbundle_dl.7z
Download: Status Legend:
Download: (OK):download completed.
Checking hash of Microsoft.WindowsTerminal_Win10_1.15.2524.0_8wekyb3d8bbwe.msixbundle ... ok.
Extracting dl.7z ... done.
Running pre_install script...
Running installer script...
Linking ~\scoop\apps\WindowsTerminal-Portable\current => ~\scoop\apps\WindowsTerminal-Portable\1.15.2524.0
Creating shim for 'WindowsTerminal'.
Creating shim for 'wt'.
Creating shortcut for Windows Terminal (WindowsTerminal.exe)
'WindowsTerminal-Portable' (1.15.2524.0) was installed successfully!`

it fixed now, thanks.
